#!/bin/bash

# citecount
# returns total citations for Google Scholar cluster IDs
# uses scholar.py at https://github.com/ckreibich/scholar.py

citations="0"
for cid in $@ ; do
    cites=`scholar.py/scholar.py -C $cid | grep '^  *Citations' | sed 's/^[^0-9]*//' | head -1`
    if [ "$cites" = "" ]
    then
	echo "citecount: No citations for $cid" 1>&2
    else
	echo "citecount: $cites citations for $cid" 1>&2
	citations=$[$citations+$cites]
    fi
done 
echo "$citations"
